=== espertechinc/esper/esper/etc/regression/simpleSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2005 rel. 3 U (http://www.altova.com) by Pablo Polvorin (ACHA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ss="samples:schemas:simpleSchema" targetNamespace="samples:schemas:simpleSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="simpleEvent">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:all>
				<xs:element name="nested1">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="prop1" type="xs:string"/>
							<xs:element name="prop2" type="xs:boolean"/>
							<xs:element name="nested2">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="prop3" type="xs:int" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="attr1" type="xs:string" use="required"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="prop4">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute form="qualified" name="attr2" type="xs:boolean" use="optional"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="nested3">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nested4" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="prop5" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="id" type="xs:ID" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:all>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== espertechinc/esper/common-xmlxsd/etc/regression/simpleWithSchema.xml
<!--
Schema provided, can access atribute values. Element and attribute types
are resolved well. 
If use with a namespace-aware parser, then SimpleXMLEventType cannot handle it 
(not know the nampespace of each node/attribute) and MUST be done through a SchemaXMLEventType
-->

<simpleEvent xmlns="samples:schemas:simpleSchema" 
  xmlns:ss="samples:schemas:simpleSchema" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
  xsi:schemaLocation="samples:schemas:simpleSchema simpleSchema.xsd">
	<nested1 attr1="SAMPLE_ATTR1">
		<prop1>SAMPLE_V1</prop1>
		<prop2>true</prop2>
		<nested2>
			<prop3>3</prop3>
			<prop3>4</prop3>
			<prop3>5</prop3>
		</nested2>
	</nested1>
	<prop4 ss:attr2="true">SAMPLE_V6</prop4>
	<nested3>
		<nested4 id="a">
			<prop5>SAMPLE_V7</prop5>
			<prop5>SAMPLE_V8</prop5>
		</nested4>
		<nested4 id="b">
			<prop5>SAMPLE_V9</prop5>
		</nested4>
		<nested4 id="c">
			<prop5>SAMPLE_V10</prop5>
			<prop5>SAMPLE_V11</prop5>
		</nested4>
	</nested3>
</simpleEvent>
