=== espertechinc/esper/esper-regression/etc/regression/mediaOrderSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="mediaorder">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="orderId" type="xs:string"/>
        <xs:element ref="items" maxOccurs="1" />
        <xs:element ref="books" maxOccurs="1" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="items">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="item" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="books">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="book" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="item">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="itemId" type="xs:string"/>
        <xs:element name="productId" type="xs:string"/>
        <xs:element name="amount" type="xs:int"/>
        <xs:element name="price" type="xs:double"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="book">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="bookId" type="xs:string"/>
        <xs:element name="author" type="xs:string"/>
        <xs:element ref="review" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="review">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="reviewId" type="xs:string"/>
        <xs:element name="comment" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== espertechinc/esper/esper-regression/etc/regression/mediaOrderTwo.xml
<?xml version="1.0" encoding="UTF-8"?>
<mediaorder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mediaOrderSchema.xsd">
  <orderId>PO200901</orderId>
  <items>
    <item>
      <itemId>200001</itemId>
      <productId>B006</productId>
      <amount>7</amount>
      <price>7.45</price>
    </item>
    <item>
      <itemId>200002</itemId>
      <productId>B005</productId>
      <amount>1</amount>
      <price>67.99</price>
    </item>
    <item>
      <itemId>200003</itemId>
      <productId>B007</productId>
      <amount>0</amount>
      <price>0</price>
    </item>
    <item>
      <itemId>200004</itemId>
      <productId>B005</productId>
      <amount>2</amount>
      <price>63.99</price>
    </item>
  </items>
  <books>
    <book>
      <bookId>B005</bookId>
      <author>Heinlein</author>
      <review>
        <reviewId>1</reviewId>
        <comment>best book ever</comment>
      </review>
      <review>
        <reviewId>2</reviewId>
        <comment>would recommend</comment>
      </review>
    </book>
    <book>
      <bookId>B006</bookId>
      <author>Isaac Asimov</author>
    </book>
    <book>
      <bookId>B008</bookId>
      <author>Ian M Banks</author>
    </book>
  </books>
</mediaorder>

=== espertechinc/esper/esper/etc/regression/mediaOrderOne.xml
<?xml version="1.0" encoding="UTF-8"?>
<mediaorder xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="mediaOrderSchema.xsd">
  <orderId>PO200901</orderId>
  <items>
    <item>
      <itemId>100001</itemId>
      <productId>B001</productId>
      <amount>10</amount>
      <price>11.95</price>
    </item>
  </items>
  <books>
    <book>
      <bookId>B001</bookId>
      <author>Orson Scott Card</author>
      <review>
        <reviewId>1</reviewId>
        <comment>best book ever</comment>
      </review>
    </book>
    <book>
      <bookId>B002</bookId>
      <author>Isaac Asimov</author>
    </book>
  </books>
</mediaorder>
